### ISSUE TITLE
Поддержка Front Matter

### ISSUE THREAD

**Issue by axaxaman** [razrabs-media/editorial#11]
Привет, кажется, если бы в md файлах поддерживались шаблоны front matter, было бы значительно проще.

https://markdoc.io/docs/frontmatter

Автор статьи мог бы туда добавлять всё, что необходимое и прочую важную информацию, сейчас же управлять какой-то метаинфой очень сложно.

А так можно было бы в каждой статье писать:
```md
---
title: Статья про статью
slug: statya-pro-statyu
labels:
  - tag1
  - tag2
---
```

и наверняка есть уже ряд метаданных, которые там было бы проще собирать.
не уверен, что это в этот репозиторий, но пока пусть тут побудет

**Comment by prozoroff** [comment]
+!

Слаги очень нужны, guid в url - это, конечно, сильно)

**Comment by gwer** [comment]
Ну хз.

Для слагов не нужен front matter. Более того, он лишь усложнит ситуацию и увеличит вероятность конфликтов (плохо отслеживаемых к тому же).

Слаг выводится из расположения документа в файловой системе. Однозначно, человекочитаемо и с гарантированной защитой от конфликтов (никто не сможет положить два файла по одному пути). Ну только если файловая система будет регистрозависимой, а сервер — нет.

Для тегов, возможно, это было бы удобно. Но фритекст в тегах ведёт к тому, что они плодятся, дублируются. В общем, тут надо хорошо подумать.

А тайтл — ну с ним-то никаких проблем.
