### ISSUE TITLE
Нет прав.

### ISSUE THREAD

**Issue by mihailbishkek** [razrabs-media/editorial#13]
Нет прав на запись в репу! 

![изображение](https://user-images.githubusercontent.com/18412931/182310880-1e1da0f6-d0c9-40bb-beab-8f401957dffe.png)

**Comment by StarHamster** [comment]
А зачем они вам? Клонируете репозиторий, вносите свои изменения/пишете статью, делаете пуллреквест. Подробнее описано [здесь](https://github.com/razrabs-media/editorial#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D0%BE%D1%81%D1%82%D0%BE%D0%B2).

Единственная проблема — вы не сможете добавить лейблы к своему ПР. Но, думаю, что если попросить добавить их в описании ПР, то ребята добавят

**Comment by philippranzhin** [comment]
> Единственная проблема — вы не сможете добавить лейблы к своему ПР. Но, думаю, что если попросить добавить их в описании ПР, то ребята добавят

Всё верно, лейблы будет расставлять редакция

**Comment by AdamArutyunov** [comment]
я думаю, можно уточнить, что нужно не клонировать, а форкать
