### ISSUE TITLE
Про SEO

### ISSUE THREAD

**Issue by frostmark** [razrabs-media/editorial#16]
Йоу @philippranzhin. А вы не боитесь, что написание статей на гитхабе как-то плохо повлияет на сео выдачу сайта? Я конечно не сео эксперт, но вроде бы пулл реквесты индексируются поисковиками и вероятнее всего могут индексироваться раньше, чем статья выкатится на прод

**Comment by frostmark** [comment]
Короче я бы проверил этот момент на вашем месте)

**Comment by batyshkaLenin** [comment]
Код с Github в целом хуже индексируется, хорошо индексируются основные страницы репозиториев с README, а остальное сильно хуже, либо вовсе не индексируется.
