### ISSUE TITLE
Типографика

### ISSUE THREAD

**Issue by AdamArutyunov** [razrabs-media/editorial#18]
Я думаю, есть смысл повысить качество текста, прогоняя его через какой-то типограф. Чтобы он заменял дефисы на тире там, где это нужно, ставил неразрывные пробелы между предлогом и словом, заменял кавычки с программистских (" ") на русские («»). Если статьи не будут соответствовать этому критерию, то, мне кажется, медиа будет больше похоже на песочницу.

(хотя можно оставить программистские кавычки как бы для небольшого шарма)

**Comment by StarHamster** [comment]
С тире согласен. Предпочитаю «ёлочки». А вот по поводу неразрывных пробелов... очень многие сейчас от них отказываются, так что «висячие» предлоги становятся нормой

**Comment by AdamArutyunov** [comment]
можно использовать студийный типограф https://design.ru/typograf

можно какой-то апишный найти

**Comment by CommanderTvis** [comment]
> Я думаю, есть смысл повысить качество текста, прогоняя его через какой-то типограф. Чтобы он заменял дефисы на тире там, где это нужно, ставил неразрывные пробелы между предлогом и словом, заменял кавычки с программистских (" ") на русские («»). Если статьи не будут соответствовать этому критерию, то, мне кажется, медиа будет больше похоже на песочницу.
> 
> (хотя можно оставить программистские кавычки как бы для небольшого шарма)

Проблема автоматической типографики в том, что много кейсов. В недавних PR я видел и "–", и " - " в качестве тире. А также "какой - то".

**Comment by CommanderTvis** [comment]
С кавычками, кстати, такая же история. Одни используют программисткие ", другие — вот такие лапки "

**Comment by AdamArutyunov** [comment]
у тебя одинаковые кавычки, мб гитхаб преобразовал

вот эти лапки?

“”

**Comment by CommanderTvis** [comment]
> у тебя одинаковые кавычки, мб гитхаб преобразовал
> 
> вот эти лапки?
> 
> “”

Да

**Comment by maksnester** [comment]
Светлая тема нужна. То что есть сейчас невозможно читать людям с неприятием белого текста на черном фоне. Глаза вытекают.

**Comment by CommanderTvis** [comment]
> Светлая тема нужна. То что есть сейчас невозможно читать людям с неприятием белого текста на черном фоне. Глаза вытекают.

Думаю, это тема для отдельной issue. Здесь скорее именно про разные спосоы графически обозначить тире

**Comment by batyshkaLenin** [comment]
Более подробно с идеями и пожеланиями лучше писать сюда: [https://github.com/razrabs-media/journal/issues](https://github.com/razrabs-media/journal/issues)

**Comment by KukkoKing** [comment]
Хрюкни

**Comment by kytta** [comment]
> можно какой-то апишный найти

Есть даже лучше: JS-либа https://github.com/typograf/typograf
