### ISSUE TITLE
Пока ничего не работает

### ISSUE THREAD

**Issue by philippranzhin** [razrabs-media/editorial#37]
Наша интеграция с гх была отлично протестирована и блестяще работала на наших аккаунтах с кучей прав

На аккаунтах без прав она не работает вообще, чиним

**Comment by StarHamster** [comment]
Закрепи эту issue и #20, чтобы точно все заметили :)

**Comment by philippranzhin** [comment]
А как их кстати крепить?

**Comment by StarHamster** [comment]
Справа внизу под Assignees, Labels, Projects и остальными штуками

**Comment by philippranzhin** [comment]
Всё работает, всё починили
